# Generated by Django 3.2 on 2022-03-27 11:42

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpkuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='kpkuser',
            name='login',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='kpkuser',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='kpkuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='kpkuser',
            name='rules',
            field=models.BooleanField(default=True, verbose_name='Даю согласие на обработку персональных данных'),
        ),
        migrations.AlterField(
            model_name='kpkuser',
            name='surname',
            field=models.CharField(max_length=150, verbose_name='Фамилия'),
        ),
    ]
